### ISSUE TITLE
Gateway IP on non-roscore computers

### ISSUE THREAD

**Issue by derektan95** [fkie/multimaster_fkie#169]
Hi, 

First of all, thanks for this amazing package. It's really useful and intuitive to use. I wanted to seek your opinions on a specific robot setup I have. Let's use the example you have on your technical report as an illustration. 

![image](https://user-images.githubusercontent.com/48535336/136805040-35f9feca-4e8b-4a89-a1a4-0f17891645ac.png)

All 3 robots are in separate subnets, and have their own roscores and corresponding gateway IPs. However, each of the subnet's roscore is not on the gateway device, but on another computer that is linked to the same roscore in the same subnet. Both master_discovery and master_sync nodes are located on the computer where the roscore is located (not where gateway is located). 

For my use case, I have a external PC that is connected to each of the 3 gateway devices (not hosting roscore). I would simply need to subscribe / publish to the ROS topics on these gateway devices, and wouldn't involve the PCs with the roscores.

1) Is this an efficient use of bandwidth, given that our gateway IP and roscore are on separate computers? Will subscribed topics have to move from gateway computer --> roscore computer --> gateway IP before it is being sent out to the subscriber (and vice versa for publisher), or will it be directly gateway computer --> gateway IP --> subscriber subnet?

2) Are there any other unforseen issues with this setup? From this [post](https://github.com/fkie/multimaster_fkie/issues/127), it seems that I would need to the `sync_remote_nodes ` parameters?

Thanks alot!

**Comment by atiderko** [comment]
Hi, thank you, i am glad if the package is helpful for you!
The `master_dsicovery` node causes a constant load on the network (some bytes/sec) by sending the heartbeat messages for the discovery. The load of the `master_sync` depends on changes in the ROS-Network (start/stop of nodes or create/destroy topics/services). In this case the registration information are get from remote `master_discovery` and registered on local roscore.
1. The topics (subscriber and publisher) are then connected by roscore and the data should be send to subscriber directly. Without going through roscore or one of the multimaster nodes. (computer --> gateway IP --> subscriber subnet)
2. If you run roscore (with `master_discovery` and `master_sync`) on each host you use ROS-node, you don't need to change the `sync_remote_nodes` parameter ;-). Beside this all hostnames on all host should be resolvable or you set ROS_IP environment variable. Otherwise ROS will try to resolve the name and if it does not work, the messages will not be delivered.
3. Try to avoid syncing the `/ tf` topic! this causes a lot of traffic.

**Comment by derektan95** [comment]
Ah, after testing this out more, I think it's all working now. Thanks again for this wonderful package!

**Comment by derektan95** [comment]
Hi @atiderko, 

May I know why you mentioned that:
```
Try to avoid syncing the / tf topic! this causes a lot of traffic.
```

/tf topic seems rather lightweight. Is it due to the fact that some tf publishers are publishing at very high rates?

**Comment by atiderko** [comment]
Hi @derektan95 ,

this is because of the high data rates and because of the NxN relationship with TCP unicast connections. This is also true for every ROS topic, but hardly any other topic has so many subscribers/publishers.

**Comment by derektan95** [comment]
Hi @atiderko, 

That's great! Thanks for the explanation!
