### ISSUE TITLE
Handling network delay

### ISSUE THREAD

**Issue by Dave-van-der-Meer** [fkie/multimaster_fkie#172]
## Question

How does the multi-master system work with large delays in the network connecting two or multiple ROS masters? I have a system where large delays of up to 5 seconds can occur. Will this influence the multi-master system?

**Comment by atiderko** [comment]
The multimaster nodes are only really active during startup and changes of the ROS system (e.g. start of nodes). The exchange of system information is done via gRPC-TCP. On long delay the ROS changes will be recognized later on other hosts.

The FKIE multimaster does not intervene in the ROS data transmission.
Since most standard ROS communication is done over TCP, the delay will hit ROS with all the consequences that come with TCP due to high latency.

**Comment by Dave-van-der-Meer** [comment]
Okay, I understand there will be no additional issues caused by the multi-master system. Thanks.
