### ISSUE TITLE
Topics not publishing when number of computers is increased

### ISSUE THREAD

**Issue by alexglzg** [fkie/multimaster_fkie#181]
Hello,

I am working on a swarm project using multimaster to have a centralized network. We just encountered a problem, if we increase the number of robots on the same multimaster network, topics stop publishing, as if the network is saturated. We are trying to run 8 robots + a laptop (as a ground station), but we cannot incorporate more than 6 robots.

What are the limitations of using multimaster in multiple machines? We are not sure if it is a problem regarding the number of computers connected to the same master/router, or if it regards more to the amount of information transmitted by each robot.

Thank you

**Comment by atiderko** [comment]
Hi,

the multimaster nodes should not generate much network load in normal operation.
You can easily check if it is due to multimaster by using only one ROS master and setting ROS_MASTER_URI accordingly on all other machines.
In multirobot systems, the Tf-topic can generate a lot of network load. It is often worthwhile to use separate Tf-Topic for each host.
