### ISSUE TITLE
Synchronising rosout output

### ISSUE THREAD

**Issue by mitch-galea** [fkie/multimaster_fkie#191]
Hello,

We are using multimaster to synchonize a laptop and camera system connected on ethernet to a remote laptop (connected to the local laptop via a vpn connection and internet) where a RQT GUI is being used to view the camera data and control parameters. Everything is working great to sychronize the required topics and services. However we would like the rosout logging messages (generated from rospy.loginfo, rospy.logerr etc) generated on the camera system to be visible on the remote laptop in the RQT console plugin. I've seen the rosout node is in the excluded nodes but is there a way to get this to work?

**Comment by atiderko** [comment]
Due to the many connections (NxN) connections, synchronization of rosout and rosout_agg topics is disabled by default. Currently there is also no possibility to disable this via a parameter.
The easiest way to synchronize the output is to remap the /rosout topic on the camera system in combination with relay  [topic_tools/relay](http://wiki.ros.org/topic_tools/relay) the target computer. But you still can not change the loglevel via RQT.
Is this sufficient for your project? I would not like to change something in the working system if it can be avoided.
